# Your Telegram bot's token. (https://core.telegram.org/bots/api#authorizing-your-bot)
# Example: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
token: ""

# The chat_id of your Telegram group
# Example: -23612486
target: 0
