name: ${project.name}
version: ${project.version}

api: [1.0.0]
main: ${project.groupId}.${project.artifactId}.${project.name}

author: ${author}
description: ${project.description}
website: ${project.url}
